import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'James',
      email: 'admin@sample.com',
      password: bcrypt.hashSync('54321', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'BestBuy',
        logo: '/images/bestbuy.jpg',
        description: 'Best seller',
        rating: 4.5,
        numReviews: 95,
      },
    },
    {
      name: 'John',
      email: 'user@sample.com',
      password: bcrypt.hashSync('12345', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Classic Plaid Flannel Shirt',
      category: 'Gömlek',
      image: '/images/boy-shirts(1).jpg',
      price: 45,
      countInStock: 10,
      brand: 'Forever21',
      rating: 4.5,
      numReviews: 10,
      description: 'Cut and sewn for a classic fit, this long-sleeved flannel shirt warms you with style from its plaid pattern and brushed exterior. While it still has plenty of rugged appeal from its thick, tweed-like fabric, this piece feels dashing with its chest patch pocket, button-down front, and curved hem.',
    },
    {
      name: 'Water Print One-Shoulder Top',
      category: 'T-shirt',
      image: '/images/girl-shirts.jpg',
      price: 30,
      countInStock: 20,
      brand: 'Forever21',
      rating: 4.0,
      numReviews: 10,
      description: 'A knit top featuring a one-shoulder neckline, allover water print, a single cami strap, and a cropped hem.',
    },
    {
      name: 'Tropical Print Fitted Shirt',
      category: 'Gömlek',
      image: '/images/boy-shirts.jpg',
      price: 35,
      countInStock: 0,
      brand: 'Forever21',
      rating: 4.8,
      numReviews: 17,
      description: 'A fitted woven shirt featuring a tropical print, contrast chambray trim on the short sleeves, a basic collar, button-down front, and a curved hem.',
    },
    {
      name: 'High-Waisted Skinny Jeans',
      category: 'Jean',
      image: '/images/girl-jeans.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Forever21',
      rating: 4.5,
      numReviews: 14,
      description: 'A pair of denim skinny jeans featuring a high-rise waist, clean wash, traditional five-pocket construction, and a zip fly with a button closure.',
    },
    {
      name: 'Paint Splatter Distressed Jeans',
      category: 'Jean',
      image: '/images/boy-jeans.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Forever21',
      rating: 4.5,
      numReviews: 10,
      description: 'A pair of slim-fit denim jeans featuring distressed details, a paint splatter design, thigh pocket, whiskering, traditional five-pocket construction, and a zip fly with a button closure.',
    },
    {
      name: 'Reworked Skinny Jeans',
      category: 'Jean',
      image: '/images/girl-jeans(1).jpg',
      price: 90,
      countInStock: 12,
      brand: 'Forever21',
      rating: 4.5,
      numReviews: 15,
      description: 'A pair of skinny jeans featuring a reworked design, whiskering, five-pocket construction, belt loops, and a high rise.',
    },
  ],
};
export default data;
